CREATE TYPE user_role AS ENUM ('user', 'admin');

CREATE TYPE status_type AS ENUM ('backlog','started','ongoing','testing','completed','done');

CREATE TYPE change_type AS ENUM('status','assigner','assignee','comment');

CREATE TYPE notification_type AS ENUM ('assignment','mention','comment','status_change');

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar NOT NULL,
  "lastname" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" user_role NOT NULL DEFAULT 'user',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" integer NOT NULL,
  "title" varchar,
  "description" text,
  "assigned_to" integer,
  "status" status_type default 'started',
  "created_by" integer NOT NULL,
  "updated_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "teams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manager_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_teams" (
  "user_id" integer NOT NULL,
  "team_id" integer NOT NULL,
  "joined_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("user_id", "team_id")
);

CREATE TABLE "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar,
  "created_by" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "collaborations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "task_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "message" text,
  "attachment" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "collaboration_tags" (
  "collab_id" integer NOT NULL,
  "tagged_user_id" integer NOT NULL,
  "tagged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("collab_id", "tagged_user_id")
);

CREATE TABLE "collaboration_attachments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "collab_id" integer NOT NULL,
  "attachment_url" varchar,
  "uploaded_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "task_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "task_id" integer NOT NULL,
  "change" change_type,
  "old_value" text,
  "new_value" text,
  "created_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "task_id" integer,
  "to_user_id" integer,
  "from_user_id" integer,
  "type" notification_type,
  "link_to" text,
  "read" boolean DEFAULT false,
  "message" text,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "tasks"."description" IS 'Content of the description';

ALTER TABLE "tasks" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "tasks" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id");

ALTER TABLE "tasks" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "tasks" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "teams" ADD FOREIGN KEY ("manager_id") REFERENCES "users" ("id");

ALTER TABLE "user_teams" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_teams" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id");

ALTER TABLE "projects" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "collaborations" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");

ALTER TABLE "collaborations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "collaboration_tags" ADD FOREIGN KEY ("collab_id") REFERENCES "collaborations" ("id");

ALTER TABLE "collaboration_tags" ADD FOREIGN KEY ("tagged_user_id") REFERENCES "users" ("id");

ALTER TABLE "collaboration_tags" ADD FOREIGN KEY ("tagged_by") REFERENCES "users" ("id");

ALTER TABLE "collaboration_attachments" ADD FOREIGN KEY ("collab_id") REFERENCES "collaborations" ("id");

ALTER TABLE "collaboration_attachments" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");

ALTER TABLE "task_logs" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");

ALTER TABLE "task_logs" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "notification" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");

ALTER TABLE "notification" ADD FOREIGN KEY ("to_user_id") REFERENCES "users" ("id");

ALTER TABLE "notification" ADD FOREIGN KEY ("from_user_id") REFERENCES "users" ("id");
